version: "2"
services:
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.114
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_CREATE_TOPICS_SEPARATOR: "$$'\n'"
      KAFKA_CREATE_TOPICS: |
        topic-1:1:3
        topic-2:1:3
        topic-3:1:3

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.114
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3

  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.114
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3

  zookeeper1:
    image: bitnami/zookeeper:latest
    container_name: zookeeper1
    environment:
      ZOO_SERVER_ID: 1
      ZOO_SERVERS: zookeeper1:2888:3888,0.0.0.0:2888:3888,zookeeper3:2888:3888
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181"
      - "2888"
      - "3888"

  zookeeper2:
    image: bitnami/zookeeper:latest
    container_name: zookeeper2
    environment:
      ZOO_SERVER_ID: 2
      ZOO_SERVERS: zookeeper1:2888:3888,0.0.0.0:2888:3888,zookeeper3:2888:3888
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181"
      - "2888"
      - "3888"

  zookeeper3:
    image: bitnami/zookeeper:latest
    container_name: zookeeper3
    environment:
      ZOO_SERVER_ID: 3
      ZOO_SERVERS: zookeeper1:2888:3888,0.0.0.0:2888:3888,zookeeper3:2888:3888
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181"
      - "2888"
      - "3888"
